/**
 * Game 46 - Bridges (Hashi). Islands show a number. Connect islands with
 * straight bridges (single or double) so each island has exactly that many
 * bridges, no bridges cross, and every island is joined into one group.
 * Puzzles are generated by growing a random connected bridge network, then
 * hiding the bridges - so a solution always exists.
 */
import * as THREE from 'three';
import { createStage, makeTile, applyLabel, tween, popIn, Easing } from '../../shared/js/three-stage.js';

const CONFIG = {
  easy: { cols: 5, rows: 7, islands: 7, doubleChance: 0.25, extraLinks: 0 },
  medium: { cols: 6, rows: 8, islands: 11, doubleChance: 0.35, extraLinks: 1 },
  hard: { cols: 7, rows: 10, islands: 17, doubleChance: 0.45, extraLinks: 3 },
};
const CELL = 1;
const ISLAND_COLOR = 0x2f6fe0;
const DONE_COLOR = 0x18a970;
const OVER_COLOR = 0xff5c5c;
const BRIDGE_COLOR = 0xf5c542;
const DIRS = [[0, 1], [1, 0], [0, -1], [-1, 0]];

function fitDistance(host, halfW, halfH, margin = 1.08) {
  const w = host.clientWidth, h = host.clientHeight;
  let aspect = w && h ? w / h : 0.5;
  aspect = Math.max(0.4, Math.min(1.6, aspect));
  return Math.max((halfH * margin) / 0.42, (halfW * margin) / (0.42 * aspect));
}

function key(a, b) { return a < b ? `${a}-${b}` : `${b}-${a}`; }

/* Grow a random connected island network on a cols x rows grid. */
function generate(cfg) {
  let best = null;
  for (let attempt = 0; attempt < 60; attempt++) {
    const grid = Array.from({ length: cfg.rows }, () => Array(cfg.cols).fill(null)); // island idx | 'h' | 'v'
    const islands = [];
    const bridges = new Map(); // key -> { a, b, count }
    const r0 = 1 + Math.floor(Math.random() * (cfg.rows - 2));
    const c0 = Math.floor(Math.random() * cfg.cols);
    islands.push({ r: r0, c: c0 });
    grid[r0][c0] = 0;

    const nearIsland = (r, c) => DIRS.some(([dr, dc]) => {
      const rr = r + dr, cc = c + dc;
      return rr >= 0 && rr < cfg.rows && cc >= 0 && cc < cfg.cols && typeof grid[rr][cc] === 'number';
    });

    let guard = 0;
    while (islands.length < cfg.islands && guard++ < 600) {
      const from = Math.floor(Math.random() * islands.length);
      const [dr, dc] = DIRS[Math.floor(Math.random() * 4)];
      const len = 2 + Math.floor(Math.random() * 3);
      const { r, c } = islands[from];
      const tr = r + dr * len, tc = c + dc * len;
      if (tr < 0 || tr >= cfg.rows || tc < 0 || tc >= cfg.cols) continue;
      if (grid[tr][tc] !== null) continue;
      let clear = true;
      for (let s = 1; s < len; s++) if (grid[r + dr * s][c + dc * s] !== null) { clear = false; break; }
      if (!clear) continue;
      grid[tr][tc] = -1; // temporary so nearIsland ignores itself
      const crowded = nearIsland(tr, tc);
      grid[tr][tc] = null;
      if (crowded) continue;
      const idx = islands.length;
      islands.push({ r: tr, c: tc });
      grid[tr][tc] = idx;
      const mark = dr === 0 ? 'h' : 'v';
      for (let s = 1; s < len; s++) grid[r + dr * s][c + dc * s] = mark;
      bridges.set(key(from, idx), { a: from, b: idx, count: Math.random() < cfg.doubleChance ? 2 : 1 });
    }

    // extra links between islands that already see each other (adds loops)
    let extras = cfg.extraLinks;
    for (let tries = 0; extras > 0 && tries < 80; tries++) {
      const a = Math.floor(Math.random() * islands.length);
      const [dr, dc] = DIRS[Math.floor(Math.random() * 4)];
      let rr = islands[a].r + dr, cc = islands[a].c + dc, blocked = false, steps = 0;
      while (rr >= 0 && rr < cfg.rows && cc >= 0 && cc < cfg.cols && grid[rr][cc] === null) { rr += dr; cc += dc; steps++; }
      if (rr < 0 || rr >= cfg.rows || cc < 0 || cc >= cfg.cols) blocked = true;
      if (blocked || steps < 1 || typeof grid[rr][cc] !== 'number') continue;
      const b = grid[rr][cc];
      if (bridges.has(key(a, b))) continue;
      const mark = dr === 0 ? 'h' : 'v';
      for (let s = 1; s <= steps; s++) grid[islands[a].r + dr * s][islands[a].c + dc * s] = mark;
      bridges.set(key(a, b), { a: Math.min(a, b), b: Math.max(a, b), count: 1 });
      extras--;
    }

    if (!best || islands.length > best.islands.length) best = { islands, bridges };
    if (islands.length >= cfg.islands) break;
  }
  best.islands.forEach((isl, i) => {
    isl.need = 0;
    best.bridges.forEach((br) => { if (br.a === i || br.b === i) isl.need += br.count; });
  });
  return best;
}

function mount(container, difficulty, api) {
  const cfg = CONFIG[difficulty] || CONFIG.easy;
  const { islands, bridges: solution } = generate(cfg);
  const optimal = [...solution.values()].reduce((s, b) => s + b.count, 0);
  const player = new Map(); // key -> { a, b, count, group }
  let selected = -1, moves = 0, hintsUsed = 0, finished = false;
  const timers = new Set();
  const later = (fn, ms) => { const t = setTimeout(() => { timers.delete(t); fn(); }, ms); timers.add(t); return t; };

  const wrap = document.createElement('div');
  wrap.className = 'pc-stage-inner';
  wrap.innerHTML = `
    <div class="hs-meta"><span>Islands done: <span class="hs-done">0</span>/${islands.length}</span><span>Moves: <span class="hs-moves">0</span></span></div>
    <div class="pc-canvas3d hs-canvas">
      <div class="pc-overlay-bottom"><span class="pc-chip hs-chip">Tap 2 islands in a line to build a bridge</span></div>
    </div>
  `;
  container.appendChild(wrap);
  const canvasHost = wrap.querySelector('.hs-canvas');
  const doneEl = wrap.querySelector('.hs-done');
  const movesEl = wrap.querySelector('.hs-moves');

  // extra room at the bottom keeps the last row clear of the hint chip
  const CHIP_PAD = 0.6;
  const halfW = (cfg.cols * CELL) / 2 + 0.1, halfH = (cfg.rows * CELL) / 2 + 0.1 + CHIP_PAD / 2;
  const stage = createStage(canvasHost, { distance: fitDistance(canvasHost, halfW, halfH) });
  stage.world.position.y = CHIP_PAD / 2;
  const cx = (c) => (c - (cfg.cols - 1) / 2) * CELL;
  const cy = (r) => ((cfg.rows - 1) / 2 - r) * CELL;

  // faint water dots marking the grid
  const dotGeo = new THREE.CircleGeometry(0.05, 10);
  const dotMat = new THREE.MeshBasicMaterial({ color: 0xffffff, transparent: true, opacity: 0.12 });
  for (let r = 0; r < cfg.rows; r++) for (let c = 0; c < cfg.cols; c++) {
    const d = new THREE.Mesh(dotGeo, dotMat);
    d.position.set(cx(c), cy(r), -0.2);
    stage.world.add(d);
  }

  const bridgeGroup = new THREE.Group();
  stage.world.add(bridgeGroup);
  const islandMeshes = islands.map((isl, i) => {
    const m = makeTile({ w: 0.8, h: 0.8, depth: 0.3, radius: 0.4, color: ISLAND_COLOR, emissive: ISLAND_COLOR, emissiveIntensity: 0, roughness: 0.3 });
    m.position.set(cx(isl.c), cy(isl.r), 0.12);
    m.userData = { idx: i };
    applyLabel(m, String(isl.need), { size: 128, w: 0.62, h: 0.62, color: '#ffffff' });
    stage.world.add(m);
    popIn(m, { delay: i * 30 });
    return m;
  });

  function countAt(i) {
    let n = 0;
    player.forEach((b) => { if (b.a === i || b.b === i) n += b.count; });
    return n;
  }

  function cellsBetween(a, b) {
    const A = islands[a], B = islands[b], out = [];
    if (A.r === B.r) { const s = Math.sign(B.c - A.c); for (let c = A.c + s; c !== B.c; c += s) out.push([A.r, c]); }
    else { const s = Math.sign(B.r - A.r); for (let r = A.r + s; r !== B.r; r += s) out.push([r, A.c]); }
    return out;
  }

  // nearest island from `a` in the direction of `b` (must be b itself)
  function neighborToward(a, b) {
    const A = islands[a], B = islands[b];
    if (A.r !== B.r && A.c !== B.c) return false;
    const between = cellsBetween(a, b);
    return !islands.some((I, i) => i !== a && i !== b && between.some(([r, c]) => I.r === r && I.c === c));
  }

  function crossesExisting(a, b) {
    const mine = cellsBetween(a, b).map(([r, c]) => `${r},${c}`);
    const set = new Set(mine);
    const horiz = islands[a].r === islands[b].r;
    for (const [k, br] of player) {
      if (k === key(a, b) || br.count === 0) continue;
      const otherHoriz = islands[br.a].r === islands[br.b].r;
      if (otherHoriz === horiz) continue;
      if (cellsBetween(br.a, br.b).some(([r, c]) => set.has(`${r},${c}`))) return true;
    }
    return false;
  }

  function buildBridgeMesh(br) {
    const A = islands[br.a], B = islands[br.b];
    const horiz = A.r === B.r;
    const len = (horiz ? Math.abs(A.c - B.c) : Math.abs(A.r - B.r)) * CELL - 0.62;
    const g = new THREE.Group();
    const offs = br.count === 2 ? [-0.11, 0.11] : [0];
    offs.forEach((o) => {
      const m = makeTile({ w: horiz ? len : 0.13, h: horiz ? 0.13 : len, depth: 0.1, radius: 0.05, color: BRIDGE_COLOR, emissive: BRIDGE_COLOR, emissiveIntensity: 0.04, roughness: 0.45 });
      if (horiz) m.position.y = o; else m.position.x = o;
      m.userData = { bridgeKey: key(br.a, br.b) };
      g.add(m);
    });
    g.position.set((cx(A.c) + cx(B.c)) / 2, (cy(A.r) + cy(B.r)) / 2, 0.02);
    g.userData = { bridgeKey: key(br.a, br.b) };
    return g;
  }

  function setBridge(a, b, count, animate = true) {
    const k = key(a, b);
    const prev = player.get(k);
    if (prev && prev.group) {
      bridgeGroup.remove(prev.group);
      prev.group.traverse((n) => { if (n.geometry) n.geometry.dispose(); if (n.material) n.material.dispose(); });
    }
    if (count <= 0) { player.delete(k); return; }
    const br = { a: Math.min(a, b), b: Math.max(a, b), count };
    br.group = buildBridgeMesh(br);
    bridgeGroup.add(br.group);
    if (animate) {
      const horiz = islands[a].r === islands[b].r;
      br.group.scale.set(horiz ? 0.05 : 1, horiz ? 1 : 0.05, 1);
      tween(br.group.scale, { x: 1, y: 1 }, 220, Easing.outBack);
    }
    player.set(k, br);
  }

  function refreshIslands() {
    let done = 0;
    islands.forEach((isl, i) => {
      const have = countAt(i);
      const m = islandMeshes[i];
      const color = have === isl.need ? DONE_COLOR : have > isl.need ? OVER_COLOR : ISLAND_COLOR;
      if (have === isl.need) done++;
      m.material.color.set(color);
      m.material.emissive.set(color);
      const glow = i === selected ? 0.6 : have === isl.need ? 0.12 : 0;
      tween(m.material, { emissiveIntensity: glow }, 160);
      const s = i === selected ? 1.18 : 1;
      tween(m.scale, { x: s, y: s, z: s }, 160, Easing.outBack);
    });
    doneEl.textContent = done;
  }

  function connected() {
    const adj = islands.map(() => []);
    player.forEach((b) => { adj[b.a].push(b.b); adj[b.b].push(b.a); });
    const seen = new Set([0]); const stack = [0];
    while (stack.length) { const n = stack.pop(); adj[n].forEach((m) => { if (!seen.has(m)) { seen.add(m); stack.push(m); } }); }
    return seen.size === islands.length;
  }

  function checkWin() {
    if (!islands.every((isl, i) => countAt(i) === isl.need)) return;
    if (!connected()) {
      api.ui.toast('All numbers match, but every island must be joined into one group!');
      return;
    }
    finished = true;
    selected = -1;
    refreshIslands();
    islandMeshes.forEach((m, i) => later(() => tween(m.scale, { x: 1.25, y: 1.25, z: 1.25 }, 160, Easing.outBack, () => tween(m.scale, { x: 1, y: 1, z: 1 }, 200)), i * 40));
    api.ui.burstFromElement(canvasHost);
    const penalty = Math.max(0, moves + hintsUsed - optimal) + hintsUsed * 2;
    const stars = penalty <= 2 ? 3 : penalty <= 7 ? 2 : 1;
    later(() => api.win(stars, { moves, hints: hintsUsed }), 450);
  }

  function cycleBridge(a, b) {
    const k = key(a, b);
    const cur = player.has(k) ? player.get(k).count : 0;
    const next = (cur + 1) % 3;
    if (next > 0 && cur === 0 && crossesExisting(a, b)) {
      api.sound.error(); api.ui.shake(canvasHost);
      api.ui.toast("Bridges can't cross each other!");
      return false;
    }
    setBridge(a, b, next);
    moves++;
    movesEl.textContent = moves;
    if (next === 0) api.sound.move(); else api.sound.click();
    return true;
  }

  function onPointerDown(e) {
    if (finished) return;
    let hit = stage.pick(e.clientX, e.clientY, islandMeshes, false);
    if (!hit) {
      // forgiving finger taps: snap to the closest island within reach
      const p = stage.pickPlane(e.clientX, e.clientY, 0.12);
      if (p) {
        let bestD = 0.62, best = -1;
        islandMeshes.forEach((m, i) => { const d = Math.hypot(m.position.x - p.x, m.position.y + stage.world.position.y - p.y); if (d < bestD) { bestD = d; best = i; } });
        if (best >= 0) hit = { object: islandMeshes[best] };
      }
    }
    if (!hit) {
      // tapping a bridge directly cycles it too
      const bh = stage.pick(e.clientX, e.clientY, bridgeGroup.children, true);
      if (bh && bh.object.userData.bridgeKey) {
        const br = player.get(bh.object.userData.bridgeKey);
        if (br) { cycleBridge(br.a, br.b); selected = -1; refreshIslands(); checkWin(); }
        return;
      }
      if (selected >= 0) { selected = -1; refreshIslands(); }
      return;
    }
    const i = hit.object.userData.idx;
    if (selected < 0) { selected = i; api.sound.click(); refreshIslands(); return; }
    if (selected === i) { selected = -1; api.sound.click(); refreshIslands(); return; }
    const a = selected;
    if (!neighborToward(a, i)) {
      api.sound.error(); api.ui.shake(canvasHost);
      api.ui.toast('Pick an island straight up, down, left or right - with nothing in between.');
      selected = i; refreshIslands();
      return;
    }
    cycleBridge(a, i);
    selected = -1;
    refreshIslands();
    checkWin();
  }
  const el = stage.renderer.domElement;
  el.addEventListener('pointerdown', onPointerDown);

  function flash(meshes) {
    meshes.forEach((m) => tween(m.scale, { x: 1.35, y: 1.35, z: 1.35 }, 180, Easing.outBack, () => tween(m.scale, { x: 1, y: 1, z: 1 }, 220)));
  }

  function hint() {
    if (finished) return;
    // 1) remove a bridge the solution doesn't have (or has fewer of)
    for (const [k, br] of player) {
      const want = solution.has(k) ? solution.get(k).count : 0;
      if (br.count > want) {
        hintsUsed++;
        setBridge(br.a, br.b, want);
        selected = -1; refreshIslands();
        flash([islandMeshes[br.a], islandMeshes[br.b]]);
        api.sound.move();
        api.ui.toast(`${api.playerName}, that bridge was not right - I took it away.`);
        checkWin();
        return;
      }
    }
    // 2) add one missing bridge from the solution
    for (const [k, br] of solution) {
      const have = player.has(k) ? player.get(k).count : 0;
      if (have < br.count) {
        hintsUsed++;
        setBridge(br.a, br.b, have + 1);
        selected = -1; refreshIslands();
        flash([islandMeshes[br.a], islandMeshes[br.b]]);
        api.sound.click();
        api.ui.toast(`${api.playerName}, here is a bridge that belongs there!`);
        checkWin();
        return;
      }
    }
  }

  refreshIslands();

  return {
    unmount: () => {
      finished = true;
      timers.forEach(clearTimeout); timers.clear();
      el.removeEventListener('pointerdown', onPointerDown);
      stage.dispose();
      wrap.remove();
    },
    hint,
  };
}

PC.Games.register('hashi', { mount });
