/**
 * Game 45 - Mirror Beam (3D). A laser shines into the grid. Tap the
 * silver mirrors to flip them between / and \ so the beam bounces through
 * every crystal. Puzzles are generated by tracing a real beam path and
 * dropping mirrors at its turns (so a solution always exists), then the
 * mirrors are scrambled.
 */
import * as THREE from 'three';
import { createStage, makeTile, tween, popIn, Easing } from '../../shared/js/three-stage.js';

const CONFIG = {
  easy: { cols: 5, rows: 6, mirrors: [3, 4], targets: 2, decoys: 1, walls: 0 },
  medium: { cols: 6, rows: 8, mirrors: [5, 6], targets: 3, decoys: 3, walls: 1 },
  hard: { cols: 7, rows: 9, mirrors: [7, 9], targets: 3, decoys: 5, walls: 3 },
};
const CELL = 1;
const BEAM = 0xff2d6f;
const CRYSTAL_OFF = 0x6a4c9c;
const CRYSTAL_ON = 0x23d18b;

// directions as [dr, dc] with rows growing downward
const reflect = (type, [dr, dc]) => (type === '/' ? [-dc, -dr] : [dc, dr]);
const flip = (t) => (t === '/' ? '\\' : '/');

function generate(cfg) {
  const { rows, cols } = cfg;
  const inGrid = (r, c) => r >= 0 && r < rows && c >= 0 && c < cols;
  for (let attempt = 0; attempt < 4000; attempt++) {
    const wantM = cfg.mirrors[0] + Math.floor(Math.random() * (cfg.mirrors[1] - cfg.mirrors[0] + 1));
    let r, c, d;
    if (Math.random() < 0.5) { r = 1 + Math.floor(Math.random() * (rows - 2)); c = 0; d = [0, 1]; }
    else { r = rows - 1; c = 1 + Math.floor(Math.random() * (cols - 2)); d = [-1, 0]; }
    const entry = { r, c, d: d.slice() };
    const visited = new Set();
    const path = [];
    let mirrorsPlaced = 0, seg = 0, segLen = 0, ok = true;
    while (inGrid(r, c)) {
      const k = r * cols + c;
      if (visited.has(k)) { ok = false; break; }
      visited.add(k);
      const cell = { r, c, mirror: null, seg };
      path.push(cell);
      if (mirrorsPlaced < wantM && segLen >= 1 && Math.random() < 0.5) {
        const options = [[d[1], d[0]], [-d[1], -d[0]]].filter(([dr, dc]) => inGrid(r + dr, c + dc) && !visited.has((r + dr) * cols + c + dc));
        if (options.length) {
          const nd = options[Math.floor(Math.random() * options.length)];
          const t = reflect('/', d);
          cell.mirror = (t[0] === nd[0] && t[1] === nd[1]) ? '/' : '\\';
          d = nd; mirrorsPlaced++; seg++; segLen = 0;
        }
      }
      r += d[0]; c += d[1]; segLen++;
    }
    if (!ok || mirrorsPlaced !== wantM) continue;
    // targets: one in the final stretch, others on earlier (non-first) stretches
    const free = path.filter((p) => !p.mirror);
    const lastSeg = free.filter((p) => p.seg === wantM);
    if (!lastSeg.length) continue;
    const targets = [lastSeg[Math.floor(Math.random() * lastSeg.length)]];
    const segs = [];
    for (let s = 1; s < wantM; s++) segs.push(s);
    segs.sort(() => Math.random() - 0.5);
    for (const s of segs) {
      if (targets.length >= cfg.targets) break;
      const opts = free.filter((p) => p.seg === s);
      if (opts.length) targets.push(opts[Math.floor(Math.random() * opts.length)]);
    }
    if (targets.length < cfg.targets) continue;
    const onPath = new Set(path.map((p) => p.r * cols + p.c));
    const empty = [];
    for (let rr = 0; rr < rows; rr++) for (let cc = 0; cc < cols; cc++) if (!onPath.has(rr * cols + cc)) empty.push({ r: rr, c: cc });
    empty.sort(() => Math.random() - 0.5);
    if (empty.length < cfg.decoys + cfg.walls) continue;
    const decoys = empty.slice(0, cfg.decoys).map((p) => ({ ...p, mirror: Math.random() < 0.5 ? '/' : '\\' }));
    const walls = empty.slice(cfg.decoys, cfg.decoys + cfg.walls);
    return { entry, path, targets, decoys, walls };
  }
  return null;
}

function fitView(host, w, h, bottomPx) {
  const cw = host.clientWidth || 360, ch = host.clientHeight || 640;
  const aspect = cw / ch || 0.5;
  const usable = Math.max(0.6, (ch - bottomPx) / ch);
  const halfH = Math.max((h * 1.06) / (2 * usable), (w * 1.06) / (2 * aspect));
  return { halfH, shiftY: halfH * (1 - usable) };
}

function mount(container, difficulty, api) {
  const cfg = CONFIG[difficulty] || CONFIG.easy;
  const { rows, cols } = cfg;
  const puzzle = generate(cfg) || generate(CONFIG.easy);
  const timeouts = new Set();
  const later = (fn, ms) => { const t = setTimeout(() => { timeouts.delete(t); fn(); }, ms); timeouts.add(t); return t; };

  // board state: kind per cell, mirror type, and the solution type
  const cellAt = Array.from({ length: rows }, () => Array(cols).fill(null));
  puzzle.path.forEach((p) => { if (p.mirror) cellAt[p.r][p.c] = { kind: 'mirror', type: p.mirror, sol: p.mirror, onPath: true }; });
  puzzle.decoys.forEach((p) => { cellAt[p.r][p.c] = { kind: 'mirror', type: p.mirror, sol: null, onPath: false }; });
  puzzle.walls.forEach((p) => { cellAt[p.r][p.c] = { kind: 'wall' }; });
  puzzle.targets.forEach((p) => { cellAt[p.r][p.c] = { kind: 'target' }; });
  const pathMirrors = puzzle.path.filter((p) => p.mirror).map((p) => cellAt[p.r][p.c]);

  const { entry } = puzzle;
  function trace() {
    let r = entry.r, c = entry.c, d = entry.d.slice();
    const pts = [{ r: r - d[0], c: c - d[1], emit: true }];
    const lit = new Set();
    const seen = new Set();
    let end = null;
    for (let guard = 0; guard < 400; guard++) {
      if (r < 0 || r >= rows || c < 0 || c >= cols) { end = { r: r - d[0] * 0.5, c: c - d[1] * 0.5, out: true, d }; break; }
      const key = `${r},${c},${d[0]},${d[1]}`;
      if (seen.has(key)) { end = { r, c }; break; }
      seen.add(key);
      const cell = cellAt[r][c];
      if (cell && cell.kind === 'wall') { end = { r: r - d[0] * 0.5, c: c - d[1] * 0.5 }; break; }
      if (cell && cell.kind === 'target') lit.add(r * cols + c);
      if (cell && cell.kind === 'mirror') { pts.push({ r, c }); d = reflect(cell.type, d); }
      r += d[0]; c += d[1];
    }
    if (end) pts.push(end);
    return { pts, lit };
  }

  // scramble path mirrors so the puzzle starts unsolved
  for (let guard = 0; guard < 40; guard++) {
    pathMirrors.forEach((m) => { m.type = Math.random() < 0.55 ? flip(m.sol) : m.sol; });
    const wrongCount = pathMirrors.filter((m) => m.type !== m.sol).length;
    if (wrongCount >= Math.ceil(pathMirrors.length / 2) && trace().lit.size < puzzle.targets.length) break;
  }
  const minTaps = pathMirrors.filter((m) => m.type !== m.sol).length;

  let taps = 0, finished = false;

  const wrap = document.createElement('div');
  wrap.className = 'pc-stage-inner';
  wrap.innerHTML = `
    <div class="lz-meta"><span>Taps: <span class="lz-taps">0</span></span><span>Crystals: <span class="lz-lit">0</span>/${puzzle.targets.length}</span></div>
    <div class="pc-canvas3d lz-canvas">
      <div class="pc-overlay-bottom"><span class="pc-chip">Tap a mirror to flip it</span></div>
    </div>
  `;
  container.appendChild(wrap);
  const canvasHost = wrap.querySelector('.lz-canvas');
  const tapsEl = wrap.querySelector('.lz-taps');
  const litEl = wrap.querySelector('.lz-lit');

  const VIEW_W = cols * CELL + 1.5, VIEW_H = rows * CELL + 1.5;
  const fit0 = fitView(canvasHost, VIEW_W, VIEW_H, 44);
  const stage = createStage(canvasHost, { distance: fit0.halfH / 0.42 });
  const baseHalfH = fit0.halfH;
  function refit() {
    const f = fitView(canvasHost, VIEW_W, VIEW_H, 44);
    stage.camera.zoom = baseHalfH / f.halfH;
    stage.camera.updateProjectionMatrix();
    stage.world.position.y = f.shiftY;
  }
  refit();
  const ro = new ResizeObserver(refit);
  ro.observe(canvasHost);

  const cx = (c) => (c - (cols - 1) / 2) * CELL;
  const cy = (r) => ((rows - 1) / 2 - r) * CELL;

  const board = makeTile({ w: cols * CELL + 0.35, h: rows * CELL + 0.35, depth: 0.2, radius: 0.3, color: 0x24123f, roughness: 0.7 });
  board.position.set(0, 0, -0.32);
  stage.world.add(board);
  for (let r = 0; r < rows; r++) for (let c = 0; c < cols; c++) {
    const slot = makeTile({ w: 0.94, h: 0.94, depth: 0.05, radius: 0.12, color: 0x34205c, roughness: 0.8 });
    slot.position.set(cx(c), cy(r), -0.2);
    slot.castShadow = false;
    stage.world.add(slot);
  }

  // emitter
  const emitter = new THREE.Group();
  const emBody = makeTile({ w: 0.72, h: 0.72, depth: 0.4, radius: 0.18, color: 0xff4d8d, emissive: BEAM, emissiveIntensity: 0.5 });
  emitter.add(emBody);
  const nozzle = new THREE.Mesh(new THREE.CylinderGeometry(0.13, 0.17, 0.4, 16), new THREE.MeshStandardMaterial({ color: 0xffffff, emissive: BEAM, emissiveIntensity: 1.2 }));
  nozzle.position.y = 0.36;
  emitter.add(nozzle);
  emitter.rotation.z = entry.d[1] === 1 ? -Math.PI / 2 : 0; // nozzle points along +y by default (north)
  emitter.position.set(cx(entry.c - entry.d[1]) + entry.d[1] * 0.12, cy(entry.r - entry.d[0]) - entry.d[0] * 0.12, 0.05);
  stage.world.add(emitter);
  popIn(emitter, { delay: 100 });

  // cell objects
  const mirrorObjs = [];
  const crystals = new Map();
  const slabGeo = new THREE.BoxGeometry(1.02, 0.12, 0.34);
  for (let r = 0; r < rows; r++) for (let c = 0; c < cols; c++) {
    const cell = cellAt[r][c];
    if (!cell) continue;
    if (cell.kind === 'mirror') {
      const holder = new THREE.Group();
      holder.position.set(cx(c), cy(r), 0);
      holder.userData.cell = { r, c };
      const pad = makeTile({ w: 0.86, h: 0.86, depth: 0.1, radius: 0.43, color: 0x5b3aa8, emissive: 0xffd93d, emissiveIntensity: 0 });
      pad.position.z = -0.12;
      holder.add(pad);
      const slab = new THREE.Mesh(slabGeo, new THREE.MeshStandardMaterial({ color: 0xffffff, metalness: 0.6, roughness: 0.1, emissive: 0x9fd8ff, emissiveIntensity: 0.55 }));
      slab.castShadow = true;
      slab.position.z = 0.12;
      const angle = cell.type === '/' ? Math.PI / 4 : -Math.PI / 4;
      slab.rotation.z = angle;
      holder.add(slab);
      stage.world.add(holder);
      popIn(holder, { delay: 120 + (r * cols + c) * 14 });
      cell.holder = holder; cell.slab = slab; cell.pad = pad; cell.angle = angle; cell.cancel = null;
      mirrorObjs.push(holder);
    } else if (cell.kind === 'wall') {
      const wall = makeTile({ w: 0.9, h: 0.9, depth: 0.55, radius: 0.12, color: 0x4a3d66, roughness: 0.8 });
      wall.position.set(cx(c), cy(r), 0.08);
      stage.world.add(wall);
      popIn(wall, { delay: 120 + (r * cols + c) * 14 });
    } else if (cell.kind === 'target') {
      const gem = new THREE.Mesh(new THREE.OctahedronGeometry(0.3, 0), new THREE.MeshStandardMaterial({ color: CRYSTAL_OFF, emissive: CRYSTAL_ON, emissiveIntensity: 0, roughness: 0.15, metalness: 0.2, flatShading: true }));
      gem.position.set(cx(c), cy(r), 0.22);
      gem.castShadow = true;
      stage.world.add(gem);
      popIn(gem, { delay: 120 + (r * cols + c) * 14 });
      crystals.set(r * cols + c, { mesh: gem, lit: false });
    }
  }

  // beam
  const beamGroup = new THREE.Group();
  stage.world.add(beamGroup);
  const beamGeo = new THREE.BoxGeometry(1, 1, 1);
  const coreMat = new THREE.MeshBasicMaterial({ color: 0xffd6e4, toneMapped: false });
  const glowMat = new THREE.MeshBasicMaterial({ color: BEAM, transparent: true, opacity: 0.55, toneMapped: false, depthWrite: false });
  coreMat.color.multiplyScalar(1.6);
  function clearBeam() { while (beamGroup.children.length) beamGroup.remove(beamGroup.children[0]); }
  function ptXY(p) { return { x: cx(p.c), y: cy(p.r) }; }
  function drawBeam(pts) {
    clearBeam();
    for (let i = 0; i < pts.length - 1; i++) {
      const a = ptXY(pts[i]), b = ptXY(pts[i + 1]);
      const len = Math.hypot(b.x - a.x, b.y - a.y);
      if (len < 0.01) continue;
      const ang = Math.atan2(b.y - a.y, b.x - a.x);
      [[glowMat, 0.2], [coreMat, 0.07]].forEach(([mat, thick]) => {
        const seg = new THREE.Mesh(beamGeo, mat);
        seg.scale.set(len + thick, thick, thick);
        seg.position.set((a.x + b.x) / 2, (a.y + b.y) / 2, 0.24);
        seg.rotation.z = ang;
        beamGroup.add(seg);
      });
    }
  }

  function update(animate) {
    const { pts, lit } = trace();
    drawBeam(pts);
    crystals.forEach((cr, k) => {
      const on = lit.has(k);
      if (on === cr.lit) return;
      cr.lit = on;
      cr.mesh.material.color.set(on ? CRYSTAL_ON : CRYSTAL_OFF);
      if (animate) {
        tween(cr.mesh.material, { emissiveIntensity: on ? 1.3 : 0 }, 200, Easing.outCubic);
        if (on) tween(cr.mesh.scale, { x: 1.4, y: 1.4, z: 1.4 }, 150, Easing.outBack, () => tween(cr.mesh.scale, { x: 1, y: 1, z: 1 }, 200, Easing.outCubic));
      } else cr.mesh.material.emissiveIntensity = on ? 1.3 : 0;
    });
    litEl.textContent = lit.size;
    return lit.size;
  }
  update(false);

  let spinT = 0;
  const unsubTick = stage.onTick(() => {
    spinT += 0.02;
    crystals.forEach((cr) => { cr.mesh.rotation.z = spinT; cr.mesh.rotation.x = 0.5; });
    emBody.material.emissiveIntensity = 0.45 + Math.sin(spinT * 4) * 0.15;
  });

  function setMirror(cell, type) {
    if (cell.type === type) return;
    cell.type = type;
    cell.angle += Math.PI / 2;
    if (cell.cancel) cell.cancel();
    cell.cancel = tween(cell.slab.rotation, { z: cell.angle }, 180, Easing.outBack);
  }

  function checkWin(litCount) {
    if (finished || litCount < puzzle.targets.length) return;
    finished = true;
    api.sound.match ? api.sound.match() : api.sound.click();
    tween(glowMat, { opacity: 0.95 }, 300, Easing.outCubic);
    later(() => {
      api.ui.burstFromElement(canvasHost);
      const stars = taps <= minTaps + 1 ? 3 : taps <= minTaps * 2 + 3 ? 2 : 1;
      api.win(stars, { taps, best: minTaps });
    }, 600);
  }

  const canvas = stage.renderer.domElement;
  let tipShown = false;
  function onPointerDown(e) {
    if (finished) return;
    const hit = stage.pick(e.clientX, e.clientY, mirrorObjs);
    let o = hit && hit.object;
    while (o && !o.userData.cell) o = o.parent;
    if (!o) {
      // tapped something that is not a mirror
      const p = stage.pickPlane(e.clientX, e.clientY, 0);
      if (p) {
        const lx = p.x - stage.world.position.x, ly = p.y - stage.world.position.y;
        if (Math.abs(lx) < (cols * CELL) / 2 && Math.abs(ly) < (rows * CELL) / 2) {
          api.sound.error();
          api.ui.shake(canvasHost);
          if (!tipShown) { tipShown = true; api.ui.toast('Only the round silver mirrors can be flipped.'); }
        }
      }
      return;
    }
    const { r, c } = o.userData.cell;
    const cell = cellAt[r][c];
    setMirror(cell, flip(cell.type));
    taps++;
    tapsEl.textContent = taps;
    api.sound.move();
    checkWin(update(true));
  }
  canvas.addEventListener('pointerdown', onPointerDown);

  function hint() {
    if (finished) return;
    // fix the first wrong mirror along the true path - that is where the
    // beam currently goes astray
    const wrong = pathMirrors.find((m) => m.type !== m.sol);
    if (!wrong) return;
    setMirror(wrong, wrong.sol);
    taps++;
    tapsEl.textContent = taps;
    const h = wrong.holder;
    tween(h.scale, { x: 1.3, y: 1.3, z: 1.3 }, 180, Easing.outBack, () => tween(h.scale, { x: 1, y: 1, z: 1 }, 240, Easing.outCubic));
    tween(wrong.pad.material, { emissiveIntensity: 0.9 }, 160, Easing.outCubic, () => tween(wrong.pad.material, { emissiveIntensity: 0 }, 800, Easing.inOutQuad));
    api.sound.click();
    api.ui.toast(`${api.playerName}, I flipped the glowing mirror for you!`);
    checkWin(update(true));
  }

  return {
    unmount: () => {
      finished = true;
      timeouts.forEach((t) => clearTimeout(t));
      timeouts.clear();
      pathMirrors.forEach((m) => { if (m.cancel) m.cancel(); });
      unsubTick();
      ro.disconnect();
      canvas.removeEventListener('pointerdown', onPointerDown);
      clearBeam();
      beamGeo.dispose(); coreMat.dispose(); glowMat.dispose(); slabGeo.dispose();
      stage.dispose();
      wrap.remove();
    },
    hint,
    debug: () => ({ finished, taps, minTaps, mirrors: pathMirrors.length }),
  };
}

PC.Games.register('laser', { mount });
